# Generated by Django 4.2.7 on 2023-11-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Address'},
        ),
        migrations.AlterField(
            model_name='address',
            name='building_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='local_number',
            field=models.CharField(max_length=255),
        ),
    ]
